{{- range $deployment, $val := .Values.services }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .appname }}
spec:
  template:
    metadata:
      labels:
        app: {{ .appname }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .port }}
          name: {{ .name }}
{{- end}}